package com.jht.administrator.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCORE".
 */
public class Score {

    private Long id;
    private Long st_id;
    private Double score;
    private java.util.Date in_time;

    public Score() {
    }

    public Score(Long id) {
        this.id = id;
    }

    public Score(Long id, Long st_id, Double score, java.util.Date in_time) {
        this.id = id;
        this.st_id = st_id;
        this.score = score;
        this.in_time = in_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSt_id() {
        return st_id;
    }

    public void setSt_id(Long st_id) {
        this.st_id = st_id;
    }

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    public java.util.Date getIn_time() {
        return in_time;
    }

    public void setIn_time(java.util.Date in_time) {
        this.in_time = in_time;
    }

}
